---
new_page_extension: md
auto_deploy: false
admin_path: "/public/admin"
webhook_url: 
sections:
- type: directory
  path: content/pages/posts
  label: Posts
  create: all
  match: "**/*"
- type: directory
  path: content/pages
  label: Pages
  create: documents
  match: "**/*"
  exclude: content/pages/posts
- type: document
  path: content/data/config.json
  label: Config
upload_dir: public
public_path: ''
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  install_dependencies_command: npm install
  preview_docker_image: forestryio/node:12
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npm run develop
